alias k=kubectl
alias h=helm
alias kg='kubectl get'
alias kcf='kubectl create -f'
alias hi='helm install'
alias hid='helm install --dry-run'
alias drit='docker run --rm -it'
alias weather='curl http://wttr.in/manchester'
alias dc='docker-compose'
alias dcps='docker-compose ps'
alias dcr='docker-compose run'
alias dce='docker-compose exec'