# uncomment to profile prompt startup with zprof
#zmodload zsh/zprof

# vim bindings
bindkey -v

fpath=( "$HOME/.zfunctions" $fpath )
export NVM_DIR="$HOME/.nvm"
  . "$(brew --prefix nvm)/nvm.sh"

# initialize autocomplete here, otherwise functions won't be loaded
autoload -Uz compinit
compinit
zmodload zsh/complist

# Load additional config like history.zsh, etc…
for file in ~/dotfiles/zsh/{antigen,completion,config,fpath,history,path,prompt}.zsh; do
  [ -r "$file" ] && source "$file"
done
unset file

# Automatically list directory contents on `cd`.
auto-ls () {
	emulate -L zsh;
	# explicit sexy ls'ing as aliases arent honored in here.
	hash gls >/dev/null 2>&1 && CLICOLOR_FORCE=1 gls -aFh --color --group-directories-first || ls
}
chpwd_functions=( auto-ls $chpwd_functions )

# uncomment to finish profiling
#zprof

# Load default dotfiles
#source ~/.bash_profile

#Iterm2
source ~/.iterm2_shell_integration.`basename $SHELL`


test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
google() { open -a "Google Chrome" "http://www.google.com/search?q=$1"; } 

#eval "$(docker-machine env default)"

alias vssh='vagrant ssh'
alias vup='vagrant up'
alias g=git
alias 'git_volatile'='git log --pretty=format: --name-only | sort | uniq -c | sort -rg | head -10'
#alias composer='php -d memory_limit=-1 /usr/local/bin/composer'
alias git='nocorrect git' 
alias dconsole='docker-compose exec web ./app/console'
alias ez='docker-compose exec ezweb ./app/console'
alias drun='docker-compose exec web ./bin/console'
alias composer='php -d memory_limit=-1 /usr/local/bin/composer --ignore-platform-reqs'
alias weather='curl http://wttr.in/manchester'
alias tofana='curl http://wttr.in/~Tofane'
alias pods='echo "\e[31m $NS \e[0m"; kubectl --namespace=$NS get pods --show-labels -o wide'
alias names='kubectl get namespaces'
alias prodcontext='kubectl config use-context ft-prod; NS=XXXXXXXXXXXXXXXXXXX; names;'
alias devcontext='kubectl config use-context ft-dev'
alias dspec='docker-compose exec web ./bin/phpspec'
#eval $(thefuck --alias)
alias remove_old_branches="git fetch -p && git branch -vv --no-color | grep gone | cut -d ' ' -f3 | xargs git branch -d"
alias services='kubectl describe services --namespace=$NS'
alias htsiUATcontext='kubectl config use-context ft-staging; export NS=htsi-fe-uat'
alias icintegration='kubectl config use-context us-staging; export NS=ic-integration; echo NS=$NS'
alias icuat='kubectl config use-context us-staging; export NS=ic-uat; echo NS=$NS'
alias kget='echo "\e[31m $NS \e[0m"; kubectl --namespace=$NS get'
alias kgety='kubectl --namespace=$NS -o yaml get'
alias get='kube get'
alias dc='docker-compose exec web ./app/console'
alias e='docker-compose exec web'
alias ftaintkube='kubectl -n ftadviser-integration'
alias ftauatkube='kubectl -n ftadviser-uat'

source <(kubectl completion zsh)



# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/wodor/Downloads/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/wodor/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/wodor/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/wodor/Downloads/google-cloud-sdk/completion.zsh.inc'; fi
