# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#zmodload zsh/zprof
# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/artwielogorski/.oh-my-zsh"
DEFAULT_USER=`whoami`
export EDITOR='vim'

# Load additional config like history.zsh, etc…
# for file in ~/code/dotfiles/zsh/{completion,config,fpath,history,path,fasd,aliases}.zsh; do
#   [ -r "$file" ] && source "$file"
# done
# unset file
plugins=(
  git
  history-substring-search
)
# Load additional config like history.zsh, etc…
for file in ~/code/dotfiles/zsh/{completion,config,history,fasd,aliases,zinit}.zsh; do
  [ -r "$file" ] && source "$file"
done
unset file

export GOPATH="/usr/local"
export GOBIN=/usr/local/bin

export GITHUB_TOKEN=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
export GITHUB_USERNAME=wodor
export HOMESHICK_DIR=/opt/homebrew/opt/homeshick
source "/opt/homebrew/opt/homeshick/homeshick.sh"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
